name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  packages: write
  issues: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: npm run build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: npm run build:win

      - name: List built files (for debugging)
        run: ls -la dist/

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.AppImage
            dist/*.deb
        # dist/*.rpm
        # dist/*.tar.gz
        # dist/*.yml
        # dist/*.snap
        # dist/*.exe
        # dist/*.zip
        # dist/*.dmg
        # dist/*.blockmap

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
